In [ ]:
import pandas as pd
import numpy as np

In [ ]:
wom_1 = pd.read_csv('')
wom_2 = pd.read_csv('')

display(wom_1.head())

,operadora,producto,marca,precio_prepago,precio_portabilidad/renovacion,precio_normal,precio_linea_nueva,cuota_arriendo,sku,fecha_extraccion
0,WOM,Redmi Note 12 Pro 5G Black,Xiaomi,228000,204000,459990.0,204000,16000.0,001.002.2376,2026-05-13
1,WOM,Redmi Note 12 Pro 5G Blue,Xiaomi,228000,204000,459990.0,204000,23000.0,001.002.2377,2026-05-13
2,WOM,Redmi Note 12 Pro 5G White,Xiaomi,228000,204000,459990.0,204000,23000.0,001.002.2545,2026-05-13
3,WOM,Apple iPhone Air 5G 512GB Space Black,Apple,1480800,1360800,1559990.0,1360800,51300.0,001.002.2885,2026-05-13
4,WOM,ZTE Blade A56 Pro 4G 128GB Grey,ZTE,115200,103200,149990.0,103200,7500.0,001.002.2822,2026-05-13

In [ ]:
wom_total = pd.concat([wom_1, wom_2], ignore_index=True)

print(f'Filas en wom_1: {len(wom_1)}')
print(f'Filas en wom_2: {len(wom_2)}')
print(f'Total de filas después de unir: {len(wom_total)}')

display(wom_total.tail())

Filas en wom_1: 482
Filas en wom_2: 120
Total de filas después de unir: 602

,operadora,producto,marca,precio_prepago,precio_portabilidad/renovacion,precio_normal,precio_linea_nueva,cuota_arriendo,sku,fecha_extraccion
597,WOM,Redmi Note 15 Pro 5G 512GB Bundle Silver,Xiaomi,376800,340800,449990.0,340800,18000.0,001.002.2920,2026-06-22
598,WOM,Redmi Note 15 Pro 5G 512GB Black,Xiaomi,376800,340800,449990.0,340800,18000.0,001.002.2925,2026-06-22
599,WOM,Redmi Note 15 Pro 5G 512GB Silver,Xiaomi,376800,340800,449990.0,340800,18000.0,001.002.2926,2026-06-22
600,WOM,Apple iPhone 17e 5G 256GB Black,Apple,660000,660000,699990.0,660000,31500.0,001.002.2942,2026-06-22
601,WOM,Apple iPhone 17e 5G 256GB Soft Pink,Apple,660000,660000,699990.0,660000,31500.0,001.002.2944,2026-06-22

In [ ]:
wom_total.to_csv('wom_consolidado.csv', index=False)
print('Archivo exportado exitosamente')

Archivo exportado exitosamente como wom_total_unido.csv